// -----------------------------------------------------------------------------
// Auto-generated by D2Bridge Wizard
// REST CRUD for <TABLENAME>
// -----------------------------------------------------------------------------

unit <UNITNAME>;

{ Copyright <COPYRIGHTYEAR> D2Bridge Framework by Talis Jonatas Gomes }

{$IFDEF FPC}
{$mode delphi}{$H+}
{$ENDIF}

interface

uses
  Classes, SysUtils,
{$IFDEF FPC}
  fpjson,
{$ELSE}
  JSON,
{$ENDIF}
  Prism.Types,
  D2Bridge.JSON,
  D2Bridge.Rest.Server.Functions;

implementation


// ============================================================================
// GET /api/<TABLENAMELOWER>
// List all <TABLENAME>
// ============================================================================

procedure Get<TABLENAME>List(const RestSession: TD2BridgeRestSession; Request: TPrismHTTPRequest; Response: TPrismHTTPResponse);
begin
{
 with RestSession.DM.<TABLENAME> do
 begin
   Close;
   SQL.Text := 'select * from <TABLENAMELOWER>';
   Open;
 end;
 
 Response.JSON(RestSession.DM.<TABLENAME>);
} 
end;


// ============================================================================
// GET /api/<TABLENAMELOWER>/:id
// Get one row from <TABLENAME>
// ============================================================================

procedure Get<TABLENAME>(const RestSession: TD2BridgeRestSession; Request: TPrismHTTPRequest; Response: TPrismHTTPResponse);
var
 vId: Integer;
begin
 vId:= Request.ParamInt('id');

 if vId <= 0 then
 begin
  Response.JSON(HTTPStatus.ErrorNotFound, '<TABLENAME> not found');
  exit;
 end;
 
{ 
 with RestSession.DM.<TABLENAME> do
 begin
   Close;
   SQL.Text := 'select * from <TABLENAMELOWER> where id = :id';
   ParamByName('id').AsInteger := vId;
   Open;
 end;
 
 if RestSession.DM.<TABLENAME>.IsEmpty then
 begin
  Response.JSON(HTTPStatus.ErrorNotFound, '<TABLENAME> not found');
  exit; 
 end;
 
 Response.JSON(RestSession.DM.<TABLENAME>); 
} 
end;


// ============================================================================
// POST /api/<TABLENAMELOWER>
// Insert new record from <TABLENAME>
// ============================================================================

procedure Post<TABLENAME>(const RestSession: TD2BridgeRestSession; Request: TPrismHTTPRequest; Response: TPrismHTTPResponse);
begin
 if not Request.BodyIsJSONValue then
 begin
  Response.JSON(HTTPStatus.ErrorBadRequest, 'Invalid JSON Body from <TABLENAME>');
  exit;
 end;
 
{ 
 with RestSession.DM.<TABLENAME> do
 begin
   Append;
   FieldByName('name').AsString  := Request.BodyJSON.Get('name', '');
   FieldByName('price').AsFloat  := Request.BodyJSON.Get('price', 0.0);
   Post;
 end;
 
 Response.JSON(HTTPStatus.SuccessCreated, '<TABLENAME> created');
 Response.JSON('id', RestSession.DM.<TABLENAME>.FieldByName('id').AsInteger); 
} 
end;


// ============================================================================
// PUT /api/<TABLENAMELOWER>/:id
// Update <TABLENAME>
// ============================================================================

procedure Put<TABLENAME>(const RestSession: TD2BridgeRestSession; Request: TPrismHTTPRequest; Response: TPrismHTTPResponse);
var
 vId: Integer;
begin
 vId:= Request.ParamInt('id');

 if vId <= 0 then
 begin
  Response.JSON(HTTPStatus.ErrorNotFound, '<TABLENAME> not found');
  exit;
 end;

 if not Request.BodyIsJSONValue then
 begin
  Response.JSON(HTTPStatus.ErrorBadRequest, 'Invalid JSON Body from <TABLENAME>');
  exit;
 end;
 
{
 with RestSession.DM.<TABLENAME> do
 begin
   Close;
   SQL.Text := 'select * from <TABLENAMELOWER> where id = :id';
   ParamByName('id').AsInteger := vId;
   Open;
 end;

 if RestSession.DM.<TABLENAME>.IsEmpty then
 begin
   Response.JSON(HTTPStatus.ErrorNotFound, '<TABLENAME> not found');
   Exit;
 end;

 with RestSession.DM.<TABLENAME> do
 begin
   Edit;

  	if Request.BodyJSON.Find('name') <> nil then
 	FieldByName('name').AsString :=	Request.BodyJSON.Get('name', FieldByName('name').AsString);

  	if Request.BodyJSON.Find('price') <> nil then
 	FieldByName('price').AsFloat :=	Request.BodyJSON.Get('price', FieldByName('price').AsFloat);

   Post;
 end;

 Response.JSON(HTTPStatus.SuccessOK, '<TABLENAME> id ' + IntToStr(vId) + ' updated');
} 
end;


// ============================================================================
// DELETE /api/<TABLENAMELOWER>/:id
// Delete from <TABLENAME>
// ============================================================================

procedure Delete<TABLENAME>(const RestSession: TD2BridgeRestSession; Request: TPrismHTTPRequest; Response: TPrismHTTPResponse);
var
 vId: Integer;
begin
 vId:= Request.ParamInt('id');

 if vId <= 0 then
 begin
  Response.JSON(HTTPStatus.ErrorNotFound, '<TABLENAME> not found');
  exit;
 end;
 
{ 
 with RestSession.DM.<TABLENAME> do
 begin
   Close;
   SQL.Text := 'select * from <TABLENAMELOWER> where id = :id';
   ParamByName('id').AsInteger := vId;
   Open;
 end;
 
 if RestSession.DM.<TABLENAME>.IsEmpty then
 begin
   Response.JSON(HTTPStatus.ErrorNotFound, '<TABLENAME> not found');
   Exit;
 end;
 
 RestSession.DM.<TABLENAME>.Delete;
 
 Response.JSON(HTTPStatus.SuccessOK, '<TABLENAME> id ' + IntToStr(vId) + ' deleted'); 
} 
end;



// ============================================================================
// Endpoints from <TABLENAME>
// ============================================================================

initialization
  AddGet   ('/api/<TABLENAMELOWER>',      Get<TABLENAME>List, True);
  AddGet   ('/api/<TABLENAMELOWER>/:id',  Get<TABLENAME>,     True);
  AddPost  ('/api/<TABLENAMELOWER>',      Post<TABLENAME>,    True);
  AddPut   ('/api/<TABLENAMELOWER>/:id',  Put<TABLENAME>,     True);
  AddDelete('/api/<TABLENAMELOWER>/:id',  Delete<TABLENAME>,  True);


end.