// -----------------------------------------------------------------------------
// Auto-generated by D2Bridge Wizard
// REST CRUD for <TABLENAME>
// -----------------------------------------------------------------------------

unit <UNITNAME>;

{ Copyright <COPYRIGHTYEAR> D2Bridge Framework by Talis Jonatas Gomes }

{$IFDEF FPC}
{$mode delphi}{$H+}
{$ENDIF}

interface

uses
  Classes, SysUtils, DB,
{$IFDEF FPC}
  fpjson,
{$ELSE}
  JSON,
{$ENDIF}
  Prism.Types,
  D2Bridge.JSON,
  D2Bridge.Rest.Server.Functions,
  D2Bridge.Rest.Session;

implementation


// ============================================================================
// GET /api/<TABLENAMELOWER>
// List all <TABLENAME>
// ============================================================================

procedure Get<TABLENAME>List(const RestSession: TD2BridgeRestSession; Request: TPrismHTTPRequest; Response: TPrismHTTPResponse);
begin
{
 with RestSession.DM.<TABLENAME> do
 begin
   Close;
   SQL.Text := 'select * from <TABLENAMELOWER>';
   Open;
 end;
 
 if RestSession.DM.<TABLENAME>.IsEmpty then
 begin
  Response.JSON(HTTPStatus.SuccessNoContent, '<TABLENAME> not found');
  exit; 
 end; 
 
 Response.JSON(HTTPStatus.SuccessOK, RestSession.DM.<TABLENAME>);
} 
end;


// ============================================================================
// GET /api/<TABLENAMELOWER>/:id
// Get one row from <TABLENAME>
// ============================================================================

procedure Get<TABLENAME>(const RestSession: TD2BridgeRestSession; Request: TPrismHTTPRequest; Response: TPrismHTTPResponse);
var
 vId: Integer;
begin
 vId:= Request.ParamInt('id');

 if vId <= 0 then
 begin
  Response.JSON(HTTPStatus.ErrorNotFound, '<TABLENAME> not found');
  exit;
 end;
 
{ 
 with RestSession.DM.<TABLENAME> do
 begin
   Close;
   SQL.Text := 'select * from <TABLENAMELOWER> where id = :id';
   ParamByName('id').AsInteger := vId;
   Open;
 end;
 
 if RestSession.DM.<TABLENAME>.IsEmpty then
 begin
  Response.JSON(HTTPStatus.SuccessNoContent, '<TABLENAME> not found');
  exit; 
 end;
 
 Response.JSON(HTTPStatus.SuccessOK, RestSession.DM.<TABLENAME>); 
} 
end;


// ============================================================================
// POST /api/<TABLENAMELOWER>
// Insert new record from <TABLENAME>
// ============================================================================

procedure Post<TABLENAME>(const RestSession: TD2BridgeRestSession; Request: TPrismHTTPRequest; Response: TPrismHTTPResponse);
begin
 if not Request.BodyIsJSONValue then
 begin
  Response.JSON(HTTPStatus.ErrorBadRequest, 'Invalid JSON Body from <TABLENAME>');
  exit;
 end;
 
{ 
 with RestSession.DM.<TABLENAME> do
 begin
  close;
  sql.text:=
   'Select * from <TABLENAME> Where id < 0';
  open;  
 end;

 RestSession.DM.<TABLENAME>.Append;
 RestSession.DM.<TABLENAME>.FieldByName('idTable').AsString  := Request.BodyJSON.Get('idTable', '');
 RestSession.DM.<TABLENAME>.FieldByName('price').AsFloat  := Request.BodyJSON.Get('price', 0.0);

 RestSession.DM.<TABLENAME>.FromJSONObject(Request.BodyJSON, ['idTable']); 
 

 
 Response.JSON(HTTPStatus.SuccessCreated, '<TABLENAME> created');
 Response.JSON.AddPair('id', RestSession.DM.<TABLENAME>.FieldByName('id').AsInteger); 
} 
end;


// ============================================================================
// PUT /api/<TABLENAMELOWER>/:id
// Update <TABLENAME>
// ============================================================================

procedure Put<TABLENAME>(const RestSession: TD2BridgeRestSession; Request: TPrismHTTPRequest; Response: TPrismHTTPResponse);
var
 vId: Integer;
begin
 vId:= Request.ParamInt('id');

 if vId <= 0 then
 begin
  Response.JSON(HTTPStatus.ErrorNotFound, '<TABLENAME> not found');
  exit;
 end;

 if not Request.BodyIsJSONValue then
 begin
  Response.JSON(HTTPStatus.ErrorBadRequest, 'Invalid JSON Body from <TABLENAME>');
  exit;
 end;
 
 if not Assigned(Request.BodyJSON.Find('id')) then
 begin
  Response.JSON(HTTPStatus.ErrorBadRequest, 'Invalid JSON Body from <TABLENAME>');
  exit;
 end;
 
 if Request.BodyJSON.Get('id', 0) <> vId then
 begin
  Response.JSON(HTTPStatus.ErrorBadRequest, 'Error Id mismatch');
  exit;
 end;
 
{
 with RestSession.DM.<TABLENAME> do
 begin
   Close;
   SQL.Text := 'select * from <TABLENAMELOWER> where id = :id';
   ParamByName('id').AsInteger := vId;
   Open;
 end;

 if RestSession.DM.<TABLENAME>.IsEmpty then
 begin
   Response.JSON(HTTPStatus.ErrorNotFound, '<TABLENAME> not found');
   Exit;
 end;

 RestSession.DM.<TABLENAME>.FromJSONObject(Request.BodyJSON, ['idTable']);

 Response.JSON(HTTPStatus.SuccessOK, '<TABLENAME> id ' + IntToStr(vId) + ' updated');
} 
end;


// ============================================================================
// DELETE /api/<TABLENAMELOWER>/:id
// Delete from <TABLENAME>
// ============================================================================

procedure Delete<TABLENAME>(const RestSession: TD2BridgeRestSession; Request: TPrismHTTPRequest; Response: TPrismHTTPResponse);
var
 vId: Integer;
begin
 vId:= Request.ParamInt('id');

 if vId <= 0 then
 begin
  Response.JSON(HTTPStatus.ErrorNotFound, '<TABLENAME> not found');
  exit;
 end;
 
{ 
 with RestSession.DM.<TABLENAME> do
 begin
   Close;
   SQL.Text := 'select * from <TABLENAMELOWER> where id = :id';
   ParamByName('id').AsInteger := vId;
   Open;
 end;
 
 if RestSession.DM.<TABLENAME>.IsEmpty then
 begin
   Response.JSON(HTTPStatus.ErrorNotFound, '<TABLENAME> not found');
   Exit;
 end;
 
 RestSession.DM.<TABLENAME>.Delete;
 
 Response.JSON(HTTPStatus.SuccessOK, '<TABLENAME> id ' + IntToStr(vId) + ' deleted'); 
} 
end;



// ============================================================================
// Endpoints from <TABLENAME>
// ============================================================================

initialization
  AddGet   ('/api/<TABLENAMELOWER>',      Get<TABLENAME>List, True);
  AddGet   ('/api/<TABLENAMELOWER>/:id',  Get<TABLENAME>,     True);
  AddPost  ('/api/<TABLENAMELOWER>',      Post<TABLENAME>,    True);
  AddPut   ('/api/<TABLENAMELOWER>/:id',  Put<TABLENAME>,     True);
  AddDelete('/api/<TABLENAMELOWER>/:id',  Delete<TABLENAME>,  True);


end.